using Microsoft.AspNetCore.Mvc;
using steam_discovery_platform.Server.DTOs;
using steam_discovery_platform.Server.Interfaces;

namespace steam_discovery_platform.Server.Controllers
{
    /// <summary>
    /// Controller responsible for providing advanced game recommendations generated by an external Python-based engine.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class PythonRecommendationController : ControllerBase
    {
        readonly IPythonRecommendationService pythonRecommendationService;

        public PythonRecommendationController(IPythonRecommendationService pythonRecommendationService)
        {
            this.pythonRecommendationService = pythonRecommendationService;
        }

        /// <summary>
        /// Gets a list of recommended games based on a query game and specific weighting parameters.
        /// </summary>
        /// <param name="gameName">The name of the game to find similarities for.</param>
        /// <param name="genre">Weight for genre similarity (0.0 to 1.0).</param>
        /// <param name="met">Weight for Metacritic scores (0.0 to 1.0).</param>
        /// <param name="pop">Weight for popularity/recommendations (0.0 to 1.0).</param>
        /// <param name="howManyGames">Number of recommendations to retrieve.</param>
        /// <returns>A list of recommended games with basic info.</returns>
        [HttpGet("pythonRecommendation")]
        public async Task <ActionResult<PythonRecommendationResponse>> GetPythonRecommendationGames(string gameName,float genre, float met,float pop, int howManyGames, float series_penalty)
        {
            var games = await pythonRecommendationService.GetRecommendationsAsync(gameName, genre, met, pop, howManyGames, series_penalty);

            return games == null ? NotFound() : Ok(games);
        }

        [HttpGet("pythonUserRecommendation")]
        public async Task<ActionResult<PythonRecommendationResponse>> GetPythonUserRecommendationGames([FromQuery] string gameName, float genre, float met, float pop, int howManyGames)
        {
            var games = await pythonRecommendationService.GetUserRecommendationsAsync(gameName, genre, met, pop, howManyGames);
            return games == null ? NotFound() : Ok(games);
        }

    }
}
